import type { Metadata } from "next";
import "./globals.css";
import { lusitana, inter, fuenteX } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
      <p className={`${lusitana.className}`}>Hola mundo</p>
      <p className={`${fuenteX.className}`}>Hola mundo</p>
    </html>
  );
}
